### PR TITLE
Raw data file

### PR DESCRIPTION
**Pull request by lawhead**
Refactored to create the raw_data.csv file from the sqlite database at the end of acquisition, rather than during acquisition.

### CODE REVIEW

**Comment by lawhead** [comment]
In a subsequent effort I'm going to explore whether or not we can now remove a process from the acquisition client.

**Comment by tab-cmd** [comment]
we should make sure that raw_data is written at the end of existing tasks to preserve functionality.

**Comment by lawhead** [comment]
Yes, functionality should be the same. In the client stop_acquisition method it writes the raw_data.csv file.

**Comment by tab-cmd** [comment]
> Yes, functionality should be the same. In the client stop_acquisition method it writes the raw_data.csv file.

Gotcha! I see that now - thanks for doing this!

**Review by tab-cmd — APPROVED** [review]

**Review by smektala — APPROVED** [review]

**Pull request merged**
